from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Register)
admin.site.register(login)
admin.site.register(Bakery_Equipments)
admin.site.register(Customer)
admin.site.register(Customer_personal)
admin.site.register(Customer_Contact)
admin.site.register(Customer_payment)
admin.site.register(payment_installment)
admin.site.register(Employee)
admin.site.register(Employee_Personal)
admin.site.register(Employee_Contact)
admin.site.register(Employee_Previous_Details)
admin.site.register(Employee_Salary)
admin.site.register(Employee_Professional_Details)
admin.site.register(Employee_skills)
admin.site.register(Employee_attandance)
admin.site.register(Employee_Login)
admin.site.register(Employee_login_History)
admin.site.register(distributor)
admin.site.register(distributor_personal)
admin.site.register(distributor_contact)
admin.site.register(distributor_professional_details)
admin.site.register(distributor_Company)
admin.site.register(distributor_Company_Product)
admin.site.register(Purchase)
admin.site.register(Purchase_Recieve)
admin.site.register(Distributor_Payment)
admin.site.register(Purchase_Quantity)
admin.site.register(Stock)
admin.site.register(Sale)
admin.site.register(contact)
admin.site.register(term_details)
admin.site.register(Blog_details)
admin.site.register(Product)
admin.site.register(Product_details)