# Generated by Django 3.2.3 on 2021-06-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement', '0004_employee_employee_attandance_employee_contact_employee_login_employee_login_history_employee_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_FirstName', models.CharField(max_length=50)),
                ('distributor_Last_Name', models.CharField(max_length=50)),
                ('distributor_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_Company_Name', models.CharField(max_length=60)),
                ('distributor_Company_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_professional_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_Office_Address', models.CharField(max_length=100)),
                ('distributor_Office_Contact', models.CharField(max_length=30)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_CNIC', models.IntegerField()),
                ('distributor_DOB', models.DateField()),
                ('distributor_House_Number', models.IntegerField()),
                ('distributor_Street', models.CharField(max_length=100)),
                ('distributor_Town', models.CharField(max_length=100)),
                ('distributor_City', models.CharField(max_length=100)),
                ('distributor_Country', models.CharField(max_length=100)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_Contact_Number', models.CharField(max_length=30)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_Company_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_Company_Product_Name', models.CharField(max_length=50)),
                ('distributor_Company_Product_Min_Quantity', models.CharField(max_length=50)),
                ('distributor_Company_Product_Expected_Deivery', models.CharField(max_length=50)),
                ('distributor_Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor_company')),
            ],
        ),
        migrations.AddField(
            model_name='distributor_company',
            name='distributor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor_professional_details'),
        ),
    ]
