# Generated by Django 3.2.3 on 2021-06-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement', '0005_auto_20210618_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date_Time', models.DateTimeField()),
                ('Distributor_Company_Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.distributor_company_product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Recieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Recieve_Date', models.DateField()),
                ('Purchase_recieve_Bill', models.IntegerField()),
                ('Purchase_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_in_number', models.IntegerField()),
                ('Qunatit_in_litter', models.IntegerField()),
                ('Quantity_in_kg', models.IntegerField()),
                ('Purchase_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_recieve', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('Purchase_Recieve_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.purchase_recieve')),
            ],
        ),
    ]
