# Generated by Django 3.2.4 on 2021-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement', '0006_distributor_payment_purchase_purchase_quantity_purchase_recieve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Price', models.IntegerField()),
                ('Product_Discount', models.IntegerField()),
                ('Product_Description', models.CharField(max_length=150)),
                ('Product_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
