# Generated by Django 3.2.4 on 2021-06-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_para', models.CharField(max_length=150)),
                ('Blog_date', models.DateTimeField()),
                ('Blog_img', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='term_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_para', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_in_stock', models.IntegerField()),
                ('Stock_Date', models.DateField()),
                ('Purchase_Recieve_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.purchase_recieve')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Quantity', models.IntegerField()),
                ('Sale_Bill', models.IntegerField()),
                ('Sale_Date', models.DateField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.product')),
                ('Sale_By_Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.employee')),
            ],
        ),
    ]
