# Generated by Django 3.2.4 on 2021-06-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement', '0008_blog_details_contact_sale_stock_term_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Price', models.IntegerField()),
                ('Product_Discount', models.IntegerField()),
                ('Product_Description', models.CharField(max_length=150)),
                ('Product_img', models.ImageField(upload_to='images')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement.product')),
            ],
        ),
    ]
